package ru.barabo.observer.config.skad.anywork.task.nbki.gutdf.loader

import com.thoughtworks.xstream.XStream
import ru.barabo.observer.config.cbr.ptkpsd.task.f101.AbstractXmlLoader
import ru.barabo.observer.config.task.nbki.gutdf.*
import ru.barabo.observer.config.task.nbki.gutdf.general.AbstractEventData
import ru.barabo.observer.config.task.nbki.gutdf.legal.*
import ru.barabo.observer.config.task.nbki.gutdf.legal.block.*
import ru.barabo.observer.config.task.nbki.gutdf.legal.event.*
import ru.barabo.observer.config.task.nbki.gutdf.legal.title.*
import ru.barabo.observer.config.task.nbki.gutdf.physic.*
import ru.barabo.observer.config.task.nbki.gutdf.physic.block.*
import ru.barabo.observer.config.task.nbki.gutdf.physic.event.*
import ru.barabo.observer.config.task.nbki.gutdf.physic.title.*

class XmlGutDfLoader<E> : AbstractXmlLoader<E>() {

    override fun processAnnotation(xstream: XStream) {

        xstream.autodetectAnnotations(true)
        xstream.processAnnotations(AbstractEventData::class.java)
        xstream.processAnnotations(Data::class.java)
        xstream.processAnnotations(MainDocument::class.java)
        xstream.processAnnotations(Source::class.java)
        xstream.processAnnotations(FL_46_UL_36_OrgSource::class.java)
        xstream.processAnnotations(SubjectEventDataFL::class.java)
        xstream.processAnnotations(SubjectFl::class.java)
        xstream.processAnnotations(TaxNumGroup::class.java)
        xstream.processAnnotations(SubjectTitleDataFl::class.java)
        xstream.processAnnotations(FlAddress::class.java)
        xstream.processAnnotations(Fl7Social::class.java)
        xstream.processAnnotations(Fl6Tax::class.java)
        xstream.processAnnotations(Fl5PrevDoc::class.java)
        xstream.processAnnotations(Fl4Doc::class.java)
        xstream.processAnnotations(Fl3Birth::class.java)
        xstream.processAnnotations(Fl2PrevName::class.java)
        xstream.processAnnotations(FlEvent1_1::class.java)
        xstream.processAnnotations(FlEvent1_2::class.java)
        xstream.processAnnotations(FlEvent1_3::class.java)
        xstream.processAnnotations(FlEvent1_4::class.java)
        xstream.processAnnotations(FlEvent1_7::class.java)
        xstream.processAnnotations(FlEvent1_9::class.java)
        xstream.processAnnotations(FlEvent1_12::class.java)
        xstream.processAnnotations(FlEvent2_1::class.java)
        xstream.processAnnotations(FlEvent2_2::class.java)
        xstream.processAnnotations(FlEvent2_2_1::class.java)
        xstream.processAnnotations(FlEvent2_3::class.java)
        xstream.processAnnotations(FlEvent2_4::class.java)
        xstream.processAnnotations(FlEvent2_5::class.java)
        xstream.processAnnotations(FlEvent2_6::class.java)
        xstream.processAnnotations(Fl18Deal::class.java)
        xstream.processAnnotations(Fl19_1AmountInfo::class.java)
        xstream.processAnnotations(Fl19Amount::class.java)
        xstream.processAnnotations(Fl20JointDebtors::class.java)
        xstream.processAnnotations(Fl21PaymentTerms::class.java)
        xstream.processAnnotations(Fl22TotalCost::class.java)
        xstream.processAnnotations(Fl23_1ContractTermsChanges::class.java)
        xstream.processAnnotations(Fl23ContractChanges::class.java)
        xstream.processAnnotations(Fl24Fund::class.java)
        xstream.processAnnotations(Fl25_26_27_28Group::class.java)
        xstream.processAnnotations(Fl25Debt::class.java)
        xstream.processAnnotations(Fl26DebtDue::class.java)
        xstream.processAnnotations(Fl27DebtOverdue::class.java)
        xstream.processAnnotations(Fl28Payment::class.java)
        xstream.processAnnotations(Fl29_1DebtBurdenInfo::class.java)
        xstream.processAnnotations(Fl29MonthlyPayment::class.java)
        xstream.processAnnotations(Fl32_35Group::class.java)
        xstream.processAnnotations(Fl32Collateral::class.java)
        xstream.processAnnotations(Fl33Warranty::class.java)
        xstream.processAnnotations(Fl34Guarantee::class.java)
        xstream.processAnnotations(Fl35Insurance::class.java)
        xstream.processAnnotations(Fl36ProvisionPayment::class.java)
        xstream.processAnnotations(Fl38ContractEnd::class.java)
        xstream.processAnnotations(Fl39Court::class.java)
        xstream.processAnnotations(Fl54Accounting::class.java)
        xstream.processAnnotations(Fl55Application::class.java)
        xstream.processAnnotations(Fl56Participation::class.java)
        xstream.processAnnotations(Fl57Reject::class.java)
        xstream.processAnnotations(PhoneGroupFl10Contact::class.java)
        xstream.processAnnotations(PropertyIdGroupFl32_35Group::class.java)
        xstream.processAnnotations(SumGroupFl32_35Group::class.java)
        xstream.processAnnotations(UidGroupFl33Warranty::class.java)

        xstream.processAnnotations(SubjectEventDataUl::class.java)
        xstream.processAnnotations(SubjectTitleDataUl::class.java)
        xstream.processAnnotations(SubjectUl::class.java)
        xstream.processAnnotations(UlEvent1_1::class.java)
        xstream.processAnnotations(UlEvent1_2::class.java)
        xstream.processAnnotations(UlEvent1_3::class.java)
        xstream.processAnnotations(UlEvent1_4::class.java)
        xstream.processAnnotations(UlEvent1_7::class.java)
        xstream.processAnnotations(UlEvent2_1::class.java)
        xstream.processAnnotations(UlEvent2_2::class.java)
        xstream.processAnnotations(UlEvent2_2_1::class.java)
        xstream.processAnnotations(UlEvent2_3::class.java)
        xstream.processAnnotations(UlEvent2_4::class.java)
        xstream.processAnnotations(UlEvent2_5::class.java)
        xstream.processAnnotations(UlEvent2_6::class.java)
        xstream.processAnnotations(TaxNumGroupUl4Tax::class.java)
        xstream.processAnnotations(Ul1Name::class.java)
        xstream.processAnnotations(Ul2Address::class.java)
        xstream.processAnnotations(Ul3RegType::class.java)
        xstream.processAnnotations(Ul4TaxType::class.java)
        xstream.processAnnotations(Ul5Reorg::class.java)
        xstream.processAnnotations(Ul20Payment::class.java)
        xstream.processAnnotations(Ul23_26Group::class.java)
        xstream.processAnnotations(Ul23Collateral::class.java)
        xstream.processAnnotations(Ul24Warranty::class.java)
        xstream.processAnnotations(Ul25Guarantee::class.java)
        xstream.processAnnotations(Ul26Insurance::class.java)
        xstream.processAnnotations(Ul27ProvisionPayment::class.java)
        xstream.processAnnotations(Ul29ContractEnd::class.java)
        xstream.processAnnotations(Ul30Court::class.java)
        xstream.processAnnotations(Ul44Accounting::class.java)
        xstream.processAnnotations(Ul45Application::class.java)
        xstream.processAnnotations(Ul46Participation::class.java)
        xstream.processAnnotations(Ul47Reject::class.java)
        xstream.processAnnotations(PropertyIdGroupUl23_26Group::class.java)
        xstream.processAnnotations(SumGroupUl23_26Group::class.java)
        xstream.processAnnotations(UidGroupUl24Warranty::class.java)
        xstream.processAnnotations(Ul10DealUid::class.java)
        xstream.processAnnotations(Ul11Deal::class.java)
        xstream.processAnnotations(Ul12_1AmountInfo::class.java)
        xstream.processAnnotations(Ul12Amount::class.java)
        xstream.processAnnotations(Ul13JointDebtors::class.java)
        xstream.processAnnotations(Ul14PaymentTerms::class.java)
        xstream.processAnnotations(Ul15_1ContractTermsChanges::class.java)
        xstream.processAnnotations(Ul15ContractChanges::class.java)
        xstream.processAnnotations(Ul16Fund::class.java)
        xstream.processAnnotations(Ul17_18_19_20Group::class.java)
        xstream.processAnnotations(Ul17Debt::class.java)
        xstream.processAnnotations(Ul18DebtDue::class.java)
        xstream.processAnnotations(Ul19DebtOverdue::class.java)
    }
}